import { Router } from 'express';
import { z } from 'zod';
import { authenticate, requireRole } from '../../middleware/auth.js';
import { asyncHandler, validate } from '../../lib/http.js';
import { premiumService as svc } from './premium.service.js';
const router=Router();router.use(authenticate);
const kind=z.enum(['mdp','adjustment']);
const value=z.union([z.number(),z.string()]).nullable().optional();
const input=z.object({layers:z.record(z.object({minimum_premium:value,deposit_premium:value,rate_pct:value,brokerage_pct:value,initial_egnpi:value,final_egnpi:value,first_due:z.string(),instalments:value,frequency_months:value,return_premium_allowed:z.boolean().optional()}).strict()),contacts:z.record(z.string().uuid())}).strict();
const uuid=v=>validate(z.string().uuid(),v);
router.get('/premium/contracts',asyncHandler(async(_req,res)=>res.json(await svc.contracts())));
router.get('/premium/contracts/:id',asyncHandler(async(req,res)=>res.json(await svc.workspace(uuid(req.params.id)))));
router.post('/premium/contracts/:id/:kind/preview',requireRole('broker','admin'),asyncHandler(async(req,res)=>res.json(await svc.preview(uuid(req.params.id),validate(kind,req.params.kind),validate(input,req.body)))));
router.post('/premium/contracts/:id/:kind',requireRole('broker','admin'),asyncHandler(async(req,res)=>res.status(201).json(await svc.save(uuid(req.params.id),validate(kind,req.params.kind),validate(input,req.body),req.user))));
router.get('/premium/workflows/:id',asyncHandler(async(req,res)=>res.json(await svc.detail(uuid(req.params.id)))));
router.post('/premium/workflows/:id/submit',requireRole('broker','admin'),asyncHandler(async(req,res)=>res.json(await svc.submit(uuid(req.params.id),validate(z.object({reviewer_id:z.string().uuid()}).strict(),req.body).reviewer_id,req.user))));
router.post('/premium/workflows/:id/approve',requireRole('senior_broker','underwriter','admin'),asyncHandler(async(req,res)=>res.json(await svc.approve(uuid(req.params.id),req.user))));
router.post('/premium/workflows/:id/return',requireRole('senior_broker','underwriter','admin'),asyncHandler(async(req,res)=>res.json(await svc.returnDraft(uuid(req.params.id),validate(z.object({reason:z.string().min(5).max(2000)}).strict(),req.body).reason,req.user))));
router.post('/premium/workflows/:id/retry',requireRole('broker','underwriter','admin'),asyncHandler(async(req,res)=>res.json(await svc.retry(uuid(req.params.id),req.user))));
router.post('/premium/notes/:id/settle',requireRole('broker','underwriter','admin'),asyncHandler(async(req,res)=>res.json(await svc.settle(uuid(req.params.id),req.user))));
router.post('/premium/notes/:id/reconcile',requireRole('senior_broker','underwriter','admin'),asyncHandler(async(req,res)=>res.json(await svc.reconcile(uuid(req.params.id),validate(z.object({delivered:z.boolean(),reason:z.string().min(10).max(2000)}).strict(),req.body),req.user))));
router.get('/premium/notes/:id/pdf',asyncHandler(async(req,res)=>{const n=await svc.pdf(uuid(req.params.id));res.set('Content-Type','application/pdf').set('Content-Disposition',`attachment; filename="${n.note_number}.pdf"`).send(Buffer.from(n.pdf));}));
export default router;
